In [1]:
import pandas as pd
import numpy as np


In [2]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])

In [ ]:
determinant = matrix[1][1]*matrix[0][0] - matrix[0][1]*matrix[1][0]

In [3]:
def matrix_inverse_two(matrix):
    determinant = matrix[1][1]*matrix[0][0] - matrix[0][1]*matrix[1][0]
    while determinant!=0:
        try:
            matrix = np.array([[matrix[1][1], matrix[0][1]], 
                              [matrix[1][0], matrix[0][0]]])
            matrix_inverse = 1/determinant * matrix
            return matrix_inverse
            break
        except ValueError:
            print('Determinant is 0')


In [ ]:
while determinant!=0:
    try:
        matrix = np.array([[matrix[1][1], matrix[0][1]], 
                          [matrix[1][0], matrix[0][0]]])
        matrix_inverse = 1/determinant * matrix
        break
    except ValueError:
        print('Determinant is 0')

In [4]:

inverse_a = matrix_inverse_two(matrix_a)

In [5]:
i_2 = np.dot(inverse_a, matrix_a)
print(i_2)

[[3. 8.]
 [1. 3.]]


In [10]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])
def matrix_inverse_two(matrix):
    determinant = matrix[1][1]*matrix[0][0] - matrix[0][1]*matrix[1][0]
    while determinant!=0:
        try:
            matrix = np.array([[matrix[1][1], -matrix[0][1]], 
                              [-matrix[1][0], matrix[0][0]]])
            matrix_inverse = 1/determinant * matrix
            return matrix_inverse
            break
        except ValueError:
            print('Determinant is 0')
        
inverse_a = matrix_inverse_two(matrix_a)
i_2 = np.dot(inverse_a, matrix_a)
print(i_2)

[[1. 0.]
 [0. 1.]]


In [9]:
matrix_a = np.asarray([
    [1.5, 3],
    [1, 4]
])
def matrix_inverse_two(mat):
    det = (mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0])
    if det == 0:
        raise ValueError("The matrix isn't invertible")
    right_mat = np.asarray([
        [mat[1,1], -mat[0,1]],
        [-mat[1,0], mat[0,0]]
    ])
    inv_mat = np.dot(1/det, right_mat)
    return inv_mat
inverse_a = matrix_inverse_two(matrix_a)
i_2 = np.dot(inverse_a, matrix_a)
print(i_2)

[[1. 0.]
 [0. 1.]]
